#!/bin/bash
set -euo pipefail
source "$(dirname "$0")/_common.sh"

if [[ -z "${PULUMI_CONFIG_PASSPHRASE+x}" && -z "${PULUMI_CONFIG_PASSPHRASE_FILE+x}" ]]; then
  export PULUMI_CONFIG_PASSPHRASE=''
fi

pulumi -C "$KLOTHO_OUT_DIR" --stack "$KLOTHO_APP_NAME" "$@"
